### ISSUE TITLE
Would be helpful to provide setting options example

### ISSUE THREAD

**Issue by andrewbohm** [dsasko/strapi-provider-upload-imagekit#1]
Adding a config settings option in the readme would help the user understand what settings are needed just like the cloudinary upload provider.

Here is a cloudinary Example:

`./extensions/upload/config/settings.json`

```
{
  "provider": "cloudinary",
  "providerOptions": {
    "cloud_name": "cloud-name",
    "api_key": "api-key",
    "api_secret": "api-secret"
  }
}
```

**Comment by dsasko** [comment]
Thanks for the reminder @andrewbohm 
As I recall the `settings.json` file was not in the version of Strapi this plugin was developed for.
Unfortunately I didn't have time to update the plugin as both Strapi and the Imagekit API got changed. 

If you feel like it you are welcome to update it to the most current version of Strapi/Imagekit and submit a pull request.

**Comment by andrewbohm** [comment]
@dsasko sounds good.  

I'll start the process of updating to imagekit 2x and adding an example of using the `settings.json` file.

**Comment by andrewbohm** [comment]
@dsasko Pull request has been submitted and ready for review.
[pull request](https://github.com/dsasko/strapi-provider-upload-imagekit/pull/2)

**Comment by andrewbohm** [comment]
@dsasko, Can you update the NPM package to include these changes?  Thanks in advance!

**Comment by dsasko** [comment]
@andrewbohm NPM package has been updated.
