### ISSUE TITLE
Node version update to 18?

### ISSUE THREAD

**Issue by gregg-cbs** [dsasko/strapi-provider-upload-imagekit#12]
This package is using:
`{ node: '>=12.x.x <=16.x.x', npm: '>=6.0.0' }`

Any chance we can bump it up to node 18 and npm 9?

Seeing as strapi is:
```
    "node": ">=16.0.0 <=20.x.x",
    "npm": ">=6.0.0"
```

**Comment by dsasko** [comment]
Thanks for the feedback.

Actually the dependencies of this provider are what determine what node version must be used. Thankfully it seems we can align the version with the table Strapi provides in their documentation.

So the end result is and open-ended setting where we only have the minimum requirements set to `node v16` and `npm v9`

**Comment by gregg-cbs** [comment]
Thanks!
