### ISSUE TITLE
Throwing 500 when trying to delete images

### ISSUE THREAD

**Issue by gregg-cbs** [dsasko/strapi-provider-upload-imagekit#13]
I am getting a 500 error when trying to delete images. This is because the images have already been removed from imagekit.

I feel if the images do not exist in imagekit the rest of the file cleanup should still happen.

![image](https://github.com/dsasko/strapi-provider-upload-imagekit/assets/57114335/efb241bf-97e6-4a3a-9d5f-7b2192b6f5c8)

**Comment by dsasko** [comment]
> I feel if the images do not exist in imagekit the rest of the file cleanup should still happen.

@gregg-cbs thats what i would expect as well. Especially since there is a catch block that should handle errors from Imagekit. I recon its because I just proxy the error into Strapi and don't actually check why the deletion was not successful.

I will look into it 👍

**Comment by dsasko** [comment]
@gregg-cbs new version has been published to npm. Let me know if you find any more issues.

**Comment by gregg-cbs** [comment]
Ahh thanks! I will check it out now!
