### ISSUE TITLE
Strapi export throwing an error because of this plugin

### ISSUE THREAD

**Issue by gregg-cbs** [dsasko/strapi-provider-upload-imagekit#15]
Im sure you might be aware but this plugin causes strapi export to break.

I raised an issue with strapi with all the details - they lead me to you:
https://github.com/strapi/strapi/issues/18827

**Comment by dsasko** [comment]
Linked to #9

**Comment by dsasko** [comment]
@gregg-cbs sorry for the wait. A fix has been implemented. Feel free to reach out if you find any more issues or create pull requests yourself if you know how to fix it.

**Comment by dsasko** [comment]
Closing since there have been no further reports of this issue.
